name: aoc_2025
on:
  workflow_dispatch:
  push:
    paths:
      - "common/**"
      - "aoc_2025/**"

env:
  CRATE: aoc_2025

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build -p ${{ env.CRATE }}
      - name: Test
        run: cargo test -p ${{ env.CRATE }}
